# Generated by Django 4.2.30 on 2026-07-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('PRINCIPAL', 'Principal'), ('DISCIPLINE_MASTER', 'Discipline Master'), ('ACCOUNTANT', 'Accountant'), ('PROPRIETOR', 'Proprietor'), ('TEACHER', 'Teacher')], max_length=20),
        ),
    ]
